users:
  - { user: alter,
      state: absent,
      is_admin: True,
      groups: sudo,
      home: /home/alter,
      comment: Roman Dolgov,
      shell: /bin/bash,
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOCcn9IYxLS6E1NopUCmzxPBuL6a++VO7XR/kTXoPsKv rdolgov@amac
    }

