- hosts: localhost
  gather_facts: no
  vars:
    host: 127.0.0.1
    user_id: 36
  tasks:
    - name: create user
      uri:
        url:  http://{{ host }}/api/v4/users/{{ user_id }}
        method: DELETE
        headers:
          PRIVATE-TOKEN: '6FZxFszF4JC6WyyC-jS3'
        return_content: yes
      register: user_page

    - debug: msg={{ user_page }}
