- name: manage users
  become: true
  become_user: root
  become_method: sudo
  user:
    name:            "{{ item.user }}"
    shell:           "{{ item.shell }}"
    groups:          "{{ item.groups }}"
    home:            "{{ item.home }}"
    comment:         "{{ item.comment }}"
    state:           "{{ item.state | default('present') }}"
    ssh_key_comment: "{{ item.user }}"
    skeleton:        "{{ role_path }}/files/skel/{{ item.user }}"
    createhome:      yes
    append:          yes
    force:           yes
    remove:          yes
  with_items:
    - "{{ users }}"

- name: add ssh keys for users
  become: true
  become_user: root
  become_method: sudo
  authorized_key:
    user:   "{{ item.user }}"
    key:    "{{ item.key }}"
  with_items:
    - "{{ users }}"
  when:
    - item.state == 'present'

- name: manage sudoers
  lineinfile:
    dest:       /etc/sudoers.d/myOverrides
    line:       "{{ item.user }}  ALL=(ALL) NOPASSWD: ALL"
    validate:   'visudo -cf %s'
    state:      "{{ item.state }}"
  with_items:
    - "{{ users }}"
  when:
    - item.is_admin == True
